db:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=galeb_test
    ports:
    - "3306:3306"

redis:
    image: redis:2.8
    ports:
    - "6379:6379"

broker:
    image: vromero/activemq-artemis:1.5.4
    ports:
    - "61616:61616"
    - "8161:8161"
    - "5672:5672"
    environment:
    - ARTEMIS_USERNAME=guest
    - ARTEMIS_PASSWORD=guest
    - ARTEMIS_MIN_MEMORY=512M
    - ARTEMIS_MAX_MEMORY=1024M
    - ARTEMIS_PERF_JOURNAL=AUTO

manager:
    build: .
    dockerfile: Dockerfile
    environment:
        GALEB_DB_URL: jdbc:mysql://mysql.local:3306/galeb_test
        GALEB_DB_DRIVER: com.mysql.jdbc.Driver
        GALEB_DB_USER: root
        GALEB_DB_PASS: password
        REDIS_HOSTNAME: redis.local
    ports:
      - 8000:8000
    links:
      - db:mysql.local
      - redis:redis.local
